version: '3.8'

services:
  mysql:
    image: mysql:8.0.31
    restart: always
    container_name: supermarket_system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2546
    ports:
      - 3309:3306
    volumes:
      - ./dockerDB/mysql:/var/lib/mysql